apiVersion: v1
kind: Pod
metadata:
  name: app-station
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app-station
spec:
  containers:
    - name: app-station
      image: benameurfedi/ski:1.0.0
      env:
        - name: SPRING_APPLICATION_JSON
          value: '{
            "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationski?createDatabaseIfNotExist=true",
            "spring.datasource.username": "root",
            "spring.datasource.password": "",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto": "update"
          }'
      ports:
        - containerPort: 8089
          protocol: TCP
      stdin: true
      tty: true
  restartPolicy: OnFailure
